# Generated by Django 4.1.3 on 2022-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gracz', models.CharField(blank=True, max_length=50, null=True)),
                ('wynik', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
